// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGA1UVv1BDmNs0jBbkej_4p8FuIpQdVdo',
    appId: '1:608909176751:web:92dcb83438079a4ea5095a',
    messagingSenderId: '608909176751',
    projectId: 'instagram1-b331b',
    authDomain: 'instagram1-b331b.firebaseapp.com',
    storageBucket: 'instagram1-b331b.appspot.com',
    measurementId: 'G-96XCK59L80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_J_9ndY5hH183bR1ZE8nF7IHz8EZx0qI',
    appId: '1:608909176751:android:95c41615290ead00a5095a',
    messagingSenderId: '608909176751',
    projectId: 'instagram1-b331b',
    storageBucket: 'instagram1-b331b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbur9wpnQ8SMqTH82Xmv0o1OuHdmUjiUg',
    appId: '1:608909176751:ios:6cef63196c9f7698a5095a',
    messagingSenderId: '608909176751',
    projectId: 'instagram1-b331b',
    storageBucket: 'instagram1-b331b.appspot.com',
    iosClientId: '608909176751-74183qdl1op93kkfg8bjq5mb7h62h2v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbur9wpnQ8SMqTH82Xmv0o1OuHdmUjiUg',
    appId: '1:608909176751:ios:6cef63196c9f7698a5095a',
    messagingSenderId: '608909176751',
    projectId: 'instagram1-b331b',
    storageBucket: 'instagram1-b331b.appspot.com',
    iosClientId: '608909176751-74183qdl1op93kkfg8bjq5mb7h62h2v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
